[package]
name = "bran"
version = "1.0.0"
authors = ["Brian Green <briangreenery@gmail.com>"]

[dependencies]
time = "0.1.35"
clap = "2.6.0"
yaml-rust = "0.3.3"
ansi_term = "0.7.4"
libc = "0.2"

[profile.release]
lto = true
